services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sirh
      POSTGRES_PASSWORD: sirh
      POSTGRES_DB: rbac_demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
      - keycloak_data:/opt/keycloak/data

volumes:
  pgdata:
  keycloak_data:
